// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import 404Controller from "./404_controller"
application.register("404", 404Controller)

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import AlertShowMapController from "./alert_show_map_controller"
application.register("alert-show-map", AlertShowMapController)

import AlertsController from "./alerts_controller"
application.register("alerts", AlertsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
